"""create polish cases tables

Revision ID: 557627b67b00
Revises: 
Create Date: 2024-11-15 19:58:55.327264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557627b67b00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjectives',
    sa.Column('adjective_id', sa.Integer(), nullable=False),
    sa.Column('base_form', sa.String(), nullable=False),
    sa.Column('is_plural', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('adjective_id')
    )
    op.create_table('grammatical_cases',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('nouns',
    sa.Column('noun_id', sa.Integer(), nullable=False),
    sa.Column('base_form', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('is_plural', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('noun_id')
    )
    op.create_table('adjective_forms',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('adjective_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['adjective_id'], ['adjectives.adjective_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['grammatical_cases.case_id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_table('noun_forms',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('noun_id', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['grammatical_cases.case_id'], ),
    sa.ForeignKeyConstraint(['noun_id'], ['nouns.noun_id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noun_forms')
    op.drop_table('adjective_forms')
    op.drop_table('nouns')
    op.drop_table('grammatical_cases')
    op.drop_table('adjectives')
    # ### end Alembic commands ###
